name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: builder
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.4.1
        env:
          MYSQL_ROOT_PASSWORD: r
          MYSQL_DATABASE: Bankiut
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Attendre que MariaDB soit prêt
      - name: Wait for MariaDB to be ready
        run: |
          until docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") mysqladmin --user=root --password=r --host=127.0.0.1 --port=3306 ping --silent; do
            echo "Waiting for MariaDB to be ready..."
            sleep 5
          done

      # Créer la base de données projet_devops
      - name: Create databases
        run: |
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") mysql -u root -pr -e "CREATE DATABASE IF NOT EXISTS Bankiut;"
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") mysql -u root -pr -e "CREATE DATABASE IF NOT EXISTS bankiuttest;"

      # Copier et vérifier la présence de projet_devops.sql
      - name: Copy bankiut.sql
        run: |
          docker cp "$GITHUB_WORKSPACE/script/bankiut.sql" $(docker ps -q --filter "ancestor=mariadb:10.4.1"):/tmp/bankiut.sql
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") ls /tmp/bankiut.sql || echo "File not found in container!"

      # Importer projet_devops.sql
      - name: Import bankiut.sql
        run: |
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") /bin/sh -c "cat /tmp/bankiut.sql | mysql -u root -pr Bankiut"

      # Copier et importer projet_devops_test.sql
      - name: Copy bankiuttest.sql
        run: |
          docker cp "$GITHUB_WORKSPACE/script/bankiuttest.sql" $(docker ps -q --filter "ancestor=mariadb:10.4.1"):/tmp/bankiuttest.sql
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") ls /tmp/bankiuttest.sql || echo "File not found in container!"
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") /bin/sh -c "cat /tmp/bankiuttest.sql | mysql -u root -pr bankiuttest"

      # Run tests
      - name: Test with Maven
        run: mvn test --batch-mode -DargLine="--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED"

      ##### revoir cette partie pour config en focntion de votre sonarcloud
      - name: execute
        working-directory: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=IlTriki_BUT3_GR_2